#!/bin/bash

# Handles launching a module. Very easy to use:
# _exec-module <module name> [<module arg 1> <module arg 2> ...]

module="${1}"
shift

if [[ ! -f "${MODULES_BASEDIR}/${module}" ]]; then
	echo "Error: module not found: ${module}"
	exit 255
fi

args=( )
while [[ "$1" != "" ]]; do
	args+=( "$1" )
	shift
done

echo " >>> Executing '${module} ${args[@]}'..."
"${MODULES_BASEDIR}/${module}" "${args[@]}"; exit_status="$?"
echo " >>> Exiting ${module}"

exit "${exit_status}"
