#!/bin/bash

# Creates chroots for the first time, usually when installing farmerge.
# Usage:
# build dir: the place where the chroot will live
# tarball: the tarball that contains the stage5
# timezone path: the /usr/share/zoneinfo/timezone path of the current system
# tarball is stage5: used to force acceptance of the tarball, even if it doesn't
# appear to be a stage5.

required_args=( "BUILD_DIR" "TARBALL" "TIMEZONE_PATH" )
understood_args=( "${required_args[@]}" )
understood_args+=( "TARBALL_IS_STAGE5" )
source "${LIB_BASEDIR}/variable-args" || exit $?
check_for_required_args "${required_args[@]}" || exit $?

source "${LIB_BASEDIR}/output"

if [[ "${TARBALL}" == *stage5* ]]; then
	TARBALL_IS_STAGE5="1"
else
	echo "WARNING: this may not be a stage5 tarball!"
	echo "Please cancel this if you are not using a stage5 tarball, unless you know what you're doing!"
	sleep 5
fi

if [[ ! -n "${TARBALL_IS_STAGE5}" ]]; then
	echo "--$(machine_to_human_arg TARBALL) ought to reference a stage5 tarball, or whichever has the most packages."
	echo "If you are certain the tarball specified is a the right one, append --$(machine_to_human_arg TARBALL_IS_STAGE5) to arguments"
	exit 255
fi

vrun mkdir "${BUILD_DIR}" || exit $?
vrun tar -xvpf "${TARBALL}" -C "${BUILD_DIR}" || exit $?
vrun chmod +rx "${BUILD_DIR}" || exit $?
vrun ln -sf "${TIMEZONE_PATH}" "${BUILD_DIR}/etc/localtime" || exit $?
