#!/bin/bash

understood_args=( "CHROOT_ACTION" "BUILD_DIR", "BUILD_BINPKG_SUBDIR", "BUILD_DIST_SUBDIR" )
source "${LIB_BASEDIR}/variable-args" || exit $?
check_for_required_args "${understood_args[@]}"

source "${LIB_BASEDIR}/hooks"

function unmount() {
	delete_hook exit '50-unmount-'"${BUILD_DIR}"; exit_code="$?"
	[[ "${exit_code}" == "254" ]] && return
	[[ "${exit_code}" != "0" ]] && return "${exit_code}"
	
	vrun umount "${BUILD_DIR}"/dev/pts && \
	vrun umount "${BUILD_DIR}"/sys && \
	vrun umount "${BUILD_DIR}"/proc
	return $?
}

function mount() {
	add_hook exit '50-unmount-'"${BUILD_DIR}" "${MODULES_BASEDIR}/_exec-module" setup-chroot --unmount --build-dir "${BUILD_DIR}"; exit_code="$?"
	[[ "${exit_code}" == "254" ]] && return
	[[ "${exit_code}" != "0" ]] && return "${exit_code}"

	vrun mount --bind /proc "${BUILD_DIR}"/proc && \
	vrun mount --bind /sys "${BUILD_DIR}"/sys && \
	vrun mount --bind /dev/pts "${BUILD_DIR}"/dev/pts && \
	vrun cp -L /etc/resolv.conf "${BUILD_DIR}"/etc/
	
	return $?
}

function init() {
	mount || return $?

	cat > "${BUILD_DIR}/chroot.run" <<EOF
#!/bin/bash
env-update && source /etc/profile
EOF

cat "${LIB_BASEDIR}/output" >> "${BUILD_DIR}/chroot.run"

cat >> "${BUILD_DIR}/chroot.run" <<EOF
export PKGDIR="${BUILD_BINPKG_SUBDIR}"
export DISTDIR="${BUILD_DIST_SUBDIR}"
export PORTAGE_BINHOST="${MIRROR_HTTP_URI}"
export USE="bindist"

# Initial setup required before any action
which layman 2>&1 > /dev/null && vrun layman -S || exit \$?
vrun emerge --sync -v # || exit \$? # squashfs-hooks messes up this exit thing. :/
vrun emerge -GuDNv world system || exit \$?
EOF
}

function append_stdin() {
	cat >> "${BUILD_DIR}/chroot.run" || return $?
}

function execute() {
	echo "Entering chroot to launch script '${BUILD_DIR}/chroot.run'..."
	( chroot "${BUILD_DIR}" /bin/bash /chroot.run ) || return $?
}

case "${CHROOT_ACTION}" in
	init | mount | unmount | append_stdin | execute)
		"${CHROOT_ACTION}" || exit $?
		;;
	*)
		echo "Error: action not understood: ${CHROOT_ACTION}" >&2
		exit 255
		;;
done
