#!/bin/bash

understood_args=( "CHROOT_ACTION" "BUILD_DIR" "BUILD_BINPKG_SUBDIR" "BUILD_DIST_SUBDIR" )
source "${LIB_BASEDIR}/variable-args" || exit $?
check_for_required_args "${understood_args[@]}" || exit $?

source "${LIB_BASEDIR}/hooks"
source "${LIB_BASEDIR}/output"

function unmount() {
	delete_hook exit '50-unmount-'"$(basename ${BUILD_DIR})"; exit_code="$?"
	[[ "${exit_code}" != "254" ]] && [[ "${exit_code}" != "0" ]] && return "${exit_code}"
	
	vrun umount "${BUILD_DIR}"/dev/pts || return $?
	vrun umount "${BUILD_DIR}"/sys || return $?
	vrun umount "${BUILD_DIR}"/proc || return $?
}

function mount() {
	add_hook exit '50-unmount-'"$(basename ${BUILD_DIR})" "${MODULES_BASEDIR}/_exec-module" setup-chroot --chroot-action unmount --build-dir "${BUILD_DIR}" --build-binpkg-subdir "${BUILD_BINPKG_SUBDIR}" --build-dist-subdir "${BUILD_DIST_SUBDIR}"; exit_code="$?"
	[[ "${exit_code}" == "254" ]] && return
	[[ "${exit_code}" != "0" ]] && return "${exit_code}"

	vrun mount --bind /proc "${BUILD_DIR}"/proc || return $?
	vrun mount --bind /sys "${BUILD_DIR}"/sys || return $?
	vrun mount --bind /dev/pts "${BUILD_DIR}"/dev/pts || return $?
	vrun cp -L /etc/resolv.conf "${BUILD_DIR}"/etc/ || return $?
}

function init() {
	mount || return $?

	cat > "${BUILD_DIR}/chroot.run" <<EOF || return $?
#!/bin/bash
env-update && source /etc/profile
EOF

cat "${LIB_BASEDIR}/output" >> "${BUILD_DIR}/chroot.run" || return $?

cat >> "${BUILD_DIR}/chroot.run" <<EOF || return $?
export PKGDIR="${BUILD_BINPKG_SUBDIR}"
export DISTDIR="${BUILD_DIST_SUBDIR}"
export PORTAGE_BINHOST="${MIRROR_HTTP_URI}"
export USE="bindist"

# Initial setup required before any action
which layman 2>&1 > /dev/null && vrun layman -S || exit \$?
vrun emerge --sync -v # || exit \$? # squashfs-hooks messes up this exit thing. :/
vrun emerge -GuDNv world system || exit \$?
EOF
}

function append_stdin() {
	cat >> "${BUILD_DIR}/chroot.run" || return $?
}

function execute() {
	echo "Entering chroot to launch script '${BUILD_DIR}/chroot.run'..."
	chroot "${BUILD_DIR}" /bin/bash /chroot.run || return $?
}

if [[ ! -d "${BUILD_DIR}" ]]; then
	echo "Error: build dir doesn't exist: ${BUILD_DIR}"
	exit 255
fi

case "${CHROOT_ACTION}" in
	init | mount | unmount | append_stdin | execute)
		"${CHROOT_ACTION}" || exit $?
		;;
	*)
		echo "Error: action not understood: ${CHROOT_ACTION}" >&2
		exit 255
		;;
esac
