#!/bin/bash

# Handles syncing to and from the remote servers into the appropriate places in
# the build directory.

# Usage:
# sync action: can be "down" or "up", but not in between. ;)
# mirror ssh uri: the user@host uri where the mirror is located
# mirror ssh path: the /path/to/mirror on the mirror host
# staging ssh uri: the user@host uri where the staged mirror is located
# staging ssh path: the /path/to/staging on the staged mirror host
# sync dir: the directory where everything should be downloaded to
# build root dir: the base directory for /etc/portage and /var/lib/portage and
# other things like that.
# build binpkgs dir: the directory where binpkgs are to be placed. Should be
# reachable by chroot as well.
# rsync args: specify your own list of rsync arguments for syncing. NOT WORKING!

understood_args=( "SYNC_ACTION" "MIRROR_SSH_URI" "MIRROR_SSH_PATH" "STAGING_SSH_URI" "STAGING_SSH_PATH" "SYNC_DIR" "BUILD_ROOT_DIR" "BUILD_BINPKG_DIR" "RSYNC_ARGS" )
source "${LIB_BASEDIR}/variable-args" || exit $?
if [[ "${RSYNC_ARGS[@]}" == "" ]]; then
	# TODO: make it so we don't have these defaults here
	RSYNC_ARGS=( -cav --progress --delete --exclude='.lock' --exclude='.staging' )
	echo "--$(machine_to_human_arg RSYNC_ARGS) is empty, defaulting to ${RSYNC_ARGS[@]}"
fi
check_for_required_args "${understood_args[@]}" || exit $?

source "${LIB_BASEDIR}/hooks"
source "${LIB_BASEDIR}/output"

function down() {
	echo "Checking timestamp..."
	if [[ "$(ssh ${MIRROR_SSH_URI} 'cat /'"${MIRROR_SSH_PATH}"'/.timestamp')" == "$(cat ${SYNC_DIR}/.timestamp)" ]]; then
		echo "Timestamp matches, already have latest copy of mirror."
		return
	fi
	echo "Timestamp mismatch, syncing..."
	
	# Sync mirror to local
	vrun rsync "${RSYNC_ARGS[@]}" "${MIRROR_SSH_URI}:/${MIRROR_SSH_PATH}/" "${SYNC_DIR}" || return $?

	# Copy mirror's files into place
	vrun cp -v "${SYNC_DIR}/.world" "${BUILD_ROOT_DIR}/var/lib/portage/world" || return $?
	vrun rsync --delete -av "${SYNC_DIR}/.portage/" "${BUILD_ROOT_DIR}/etc/portage/" || return $?
	
	# TODO: support BUILD_BINPKG_DIR
	
	execute_hooks "sync-down" || return $?
}

function up() {
	# Copy file into local mirror copy
	vrun cp -v "${BUILD_ROOT_DIR}/var/lib/portage/world" "${SYNC_DIR}/.world" || return $?
	vrun rsync --delete -av "${BUILD_ROOT_DIR}/etc/portage/" "${SYNC_DIR}/.portage/" || return $?
	# TODO: support BUILD_BINPKG_DIR
	
	# Update time-stamp
	cat "$(date -u +%s)" > "${SYNC_DIR}/.timestamp"

	# Sync local mirror copy to staging
	vrun rsync "${RSYNC_ARGS[@]}" "${SYNC_DIR}/" "${STAGING_SSH_URI}:/${STAGING_SSH_PATH}/" || return $?
	# Copy staging into place on mirror
	vrun ssh "${MIRROR_SSH_URI}" rsync "${RSYNC_ARGS[@]}" "${STAGING_SSH_PATH}/" "${MIRROR_SSH_PATH}/" || return $?
	# TODO: support differing MIRROR_SSH_URI and STAGING_SSH_URI
	
	execute_hooks "sync-up" || return $?
}

case "${SYNC_ACTION}" in
	down | up)
		"${SYNC_ACTION}" || exit $?
		;;
	*)
		echo "Error: action not understood: ${SYNC_ACTION}" >&2
		exit 255
		;;
esac
