#!/bin/bash

# Announces verbosely the command before running it.
# Usage: vrun <command> <arguments>
function vrun () {
	local args
	args=( "${@}" )
	echo "Executing \"${args[@]}\"..."
	"${args[@]}" || return $?
}
