#!/bin/bash

if [[ -n "${IS_XPAK}" ]]; then
	exit 0
fi

verbose_redirect="/dev/null"
debug_redirect="/dev/null"
ebuilds=( )
while [[ "$1" != "" ]]; do
	if [[ "$1" == "--opt" ]]; then
		if [[ "$2" == "--verbose" ]]; then
			verbose_redirect="/dev/tty"
		elif [[ "$2" == "--debug" ]]; then
			debug_redirect="/dev/tty"
		elif [[ "$2" == "--quiet" ]]; then
			verbose_redirect="/dev/null"
			debug_redirect="/dev/null"
		fi
	elif [[ "$1" == "--action" ]]; then
		if [[ "$2" != "postinst" ]]; then
			exit 0
		fi
	elif [[ "$1" == "--target" ]]; then
		ebuilds+=( "${2}" ) # unused
	else
		ewarn "Unknown hook option: $1 $2" &> "${verbose_redirect}"
	fi
	shift 2
done

echo "${CATEGORY}/${PF}" > "${PORTAGE_TMPDIR}/ebin-todo.${PPID}"
