#!/bin/bash

ebin_lib="/usr/lib/ebin/"
source "${ROOT}"/etc/conf.d/ebin

verbose_redirect="/dev/null"
debug_redirect="/dev/null"
while [[ "$1" != "" ]]; do
	if [[ "$1" == "--opt" ]]; then
		if [[ "$2" == "--verbose" ]]; then
			verbose_redirect="/dev/tty"
		fi
		if [[ "$2" == "--debug" ]]; then
			debug_redirect="/dev/tty"
		fi
		if [[ "$2" == "--quiet" ]]; then
			verbose_redirect="/dev/null"
			debug_redirect="/dev/null"
		fi
	elif [[ "$1" == "--action" ]]; then
		if [[ "$2" != "postinst" ]]; then
			# only execute on phase postinst
			exit 0
		fi
	elif [[ "$1" == "--target" ]]; then
		src_ebuild="${2}"
	else
		ewarn "Unknown hook option: $1 $2" &> "${verbose_redirect}"
	fi
	shift 2
done

ebin_ebuild="${EBIN_OVERLAY}/${CATEGORY}/${PF}.ebuild"

"${ebin_lib}"/bin/ebin "${src_ebuild}" "${ebin_ebuild}" "=${CATEGORY}/${PF}"
exit_status="$?"

if [[ "${exit_status}" != "0" ]]; then
	eerror "ebin exited with an error"
fi

exit "${exit_status}"
